from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy


def validate_full_name(value: str):
    pass
